jobs:
  test:
    docker:
      - image: circleci/python:2.7.16
    steps:
      - checkout
      - run: 
          name: Unit test
          command: |
            pip install -r requirements.txt --user
            python tests.py
      - store_test_results:
          path: build/test-results
  merge_into_master:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "36:95:7c:54:d5:f8:63:df:96:a9:89:4c:7e:99:c4:ee<Paste>"
      - checkout
      - run: git checkout master
      - run: git merge $CIRCLE_BRANCH
      - run: git remote show origin
      - run: git push origin master 
  dockerize:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
      - run: docker build -t draagvah/codechan:latest .
      - run: docker push draagvah/codechan:latest

workflows:
  version: 2
  test_dockerize:
    jobs:
      - test:
          filters:
            branches:
              only: /feature\/.*/
      - merge_into_master:
          requires:
            - test
      # - dockerize:
          # requires:
            # - test

