jobs:
  test:
    docker:
      - image: circleci/python:2.7.16
    steps:
      - checkout
      - run: 
          name: Unit test
          command: |
            pip install -r requirements.txt --user
            python tests.py
      - store_test_results:
          path: build/test-results
  merge_into_master:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "36:95:7c:54:d5:f8:63:df:96:a9:89:4c:7e:99:c4:ee"
      - checkout
      - run: git checkout master
      - run: git merge $CIRCLE_BRANCH
      # - run: git remote show origin
      - run: git push origin master 
  dockerize:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
      - run: docker build -t draagvah/codechan:latest .
      - run: docker push draagvah/codechan:latest
  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "94:86:07:54:38:a5:91:6f:d9:b1:92:32:ac:6f:f7:3d"
      - run:
          name: Deploy on remote server
          command: ssh ubuntu@34.77.17.251 "bash codechan_update.sh"
  health_check:
    machine: true
    steps:
      - run:
          name: Test that site is up
          command: curl 34.77.17.251:5000

workflows:
  version: 2
  test_dockerize:
    jobs:
      - health_check
      # - test:
          # filters:
            # branches:
              # only: /feature\/.*/
      # - merge_into_master:
          # requires:
            # - test
      # - dockerize:
          # requires:
            # - merge_into_master
      # - deploy:
          # requires:
            # - dockerize
